### ISSUE TITLE
[Epic] Use newer/better interop primitives

### ISSUE THREAD

**Issue by mattleibow** [mono/SkiaSharp#2615]
## Description

The SkiaSharp codebase is really old and is using many old primitives. Some such things are arrays instead of renting/span or MonoTouch attributes.

This issue is an epic issue to track what we would like. If there is something I missed or some new feature that will improve performance, please add a comment or even open a PR.

### Tasks

- [ ] #2616  
     https://learn.microsoft.com/en-us/dotnet/standard/memory-and-spans/memory-t-usage-guidelines
- [ ] Switch to native function pointers  
     https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/function-pointers
     https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/unsafe-code#function-pointers
- [ ] Remove `[MonoPInvokeCallback]` attributes  
- [ ] Use Intrinsics where we can/should

**Comment by mattleibow** [comment]
LibraryImport migration completed in #2917 (August 2024). Generated bindings now use `LibraryImport` (1260 instances). The DllImport→LibraryImport migration is done. Closing.
