### ISSUE TITLE
Update Dependencies

### ISSUE THREAD

**Issue by mattleibow** [mono/SkiaSharp#718]
### Description

Source: https://github.com/mono/skia/blob/xamarin-mobile-bindings/DEPS
                   
 - [x] "third_party/externals/angle2"        (#1158)
 - [ ] "third_party/externals/dng_sdk"       
 - [x] "third_party/externals/expat" (see also #405 & #2189)
 - [x] "third_party/externals/freetype"      (https://github.com/mono/skia/pull/65)
 - [ ] "third_party/externals/googletest"    
 - [ ] "third_party/externals/harfbuzz"      
 - [ ] "third_party/externals/icu"           
 - [ ] "third_party/externals/imgui"         
 - [ ] "third_party/externals/jsoncpp"       
 - [ ] "third_party/externals/libjpeg-turbo" 
 - [ ] "third_party/externals/libpng"        
 - [ ] "third_party/externals/libwebp"       
 - [ ] "third_party/externals/lua"           
 - [ ] "third_party/externals/microhttpd"    
 - [ ] "third_party/externals/piex"          
 - [ ] "third_party/externals/rapidjson"     
 - [ ] "third_party/externals/sdl"           
 - [ ] "third_party/externals/sfntly"        
 - [ ] "third_party/externals/spirv-headers" 
 - [ ] "third_party/externals/spirv-tools"   
 - [ ] "third_party/externals/swiftshader"   
 - [x] "third_party/externals/zlib"      (#2045)

> VS bug [#744225](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/744225)

**Comment by spsteve10** [comment]
Any idea of when this update will make it into a release? Thanks!

**Comment by spsteve10** [comment]
Any idea of when this update will make it into a release? Thanks!

**Comment by mattleibow** [comment]
@spsteve10 I am not sure, this is more just to keep track of things that need to be done. No work has started yet.

**Comment by mattleibow** [comment]
FreeType has been updated to v2.10.1 in https://github.com/mono/skia/pull/65
